### ISSUE TITLE
search forces steam into unusable desktop mode

### ISSUE THREAD

**Issue by killarny** [isiah-lloyd/radiyo-steam-deck#11]
RadiYo! version: 1.2.1-1
SteamDeck OS version: 3.5.17

The search box pops up and allows entering text, but pressing enter to actually execute the search causes the whole interface to switch into Steam's desktop mode. The rest of the KDE desktop doesn't show up though, and the controller is essentially useless. A reboot seems to be the only way to get back to a usable state for the system.

**Comment by delano8** [comment]
Yep, same here. Sad that I can only listen to the 5 featured channels.

**Comment by isiah-lloyd** [comment]
@killarny @delano8 i have just submitted an update. It should be in the testing store shortly and released in a couple days or so.

**Comment by isiah-lloyd** [comment]
@killarny @delano8 Out on the testing store now. If either one you could do me a favor and test it and if it looks good leave a comment on my PR here so it can get released on to the store that would be awesome: https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/575

**Comment by killarny** [comment]
@isiah-lloyd just tested `1.3-73c25be` from the testing channel and it seems to work great. Thanks for the fix, loving this plugin!

**Comment by isiah-lloyd** [comment]
Bugfix released
