### ISSUE TITLE
API Considerations

### ISSUE THREAD

**Issue by Thijmen** [isiah-lloyd/radiyo-steam-deck#5]
Hi,

First of all - thanks for starting this plugin! I believe it can be a huge addition to our fellow Deck gamers who want to listen for some songs :) 

I see that you use http://api.dar.fm/ as API, is there any reason why you did this? E.g. have you considered http://opml.radiotime.com/Search.ashx?query=qmusic for instance which Tunein uses (apparently?)

I can see if I can help out, but I find the search results a bit unrelyable. 

Again, thanks in advance, I am sure this will add something to the Deck ecosystem :D

**Comment by isiah-lloyd** [comment]
@Thijmen 
When I developed the original RadiYo (a discord bot), I was using radiotime at first but found multiple issues. 

1. It is undocumented (well technically it does have some documentation on a wiki that is now only available on the Wayback machine) and not really for personal use like this.
2. It is in fact owned by TuneIn, which I feel like is a liability as they would have a reason to want to shutdown the API without notice to force people to use their app. (I also in general dislike TuneIn).
3.  If their database was wrong or was missing stations you are SOL. (dar.fm has a user editable database)
4.  After I started using dar.fm I reached out to them and now have a personal relationship with the founder which is nice for support. 
5. dar.fm has some interesting API features such as the trending stations and currently playing song.

I would be happy to see outside contributions! If you have interest in the dar.fm API their docs are here:  https://docs.google.com/document/d/12HNoXI-z40QLQiSi30g2qSWb8U9YbMd4u5_jrre-YTw/edit
